---
- name: Get hostname and IP address of Alpine hosts
  hosts: web_servers
  gather_facts: yes
  become: true
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: yes
        upgrade: yes

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        upgrade: dist

    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common